### ISSUE TITLE
unsatisfied instance

### ISSUE THREAD

**Issue by DevonFulcher** [dfremont/maxcount#1]
I am creating a Max 3-SAT solver myself and I came across an instance of 3-SAT that 7/8 of the clauses could not be satisfied. Perhaps I am formulating the instance wrong? Do you have any thoughts? Thanks in advance. Here is the instance:
number of clauses = 31
number of variables = 4
clauses = [(-4, 2, 2), (-1, -1, 3), (-4, 1, 3), (-3, -2, 3), (-3, 2, 3),
               (-4, 1, 4), (1, 1, 1), (-3, 2, 3), (-3, -1, 2), (-4, 2, 4),
               (-3, -3, 4), (-2, -2, 1), (-4, -2, 1), (2, 4, 4), (-3, 2, 2),
               (-2, -1, 1), (-1, -1, 4), (-3, -2, 4), (-3, -2, 3), (-2, -2, -2),
               (1, 3, 4), (-1, -1, 2), (-4, -2, -2), (-4, -1, -1), (-4, -3, 2),
               (2, 2, 2), (-1, -1, 3), (-1, 4, 4), (-1, 1, 2), (-4, -2, -2), (-3, 2, 2)]

**Comment by dfremont** [comment]
MaxCount is not a MaxSAT solver, it is a Max#SAT solver (note the # sign). These are very different problems: you could use our solver to solve MaxSAT problems, but you'd have to perform a reduction first (see [our paper](https://www2.eecs.berkeley.edu/Pubs/TechRpts/2016/EECS-2016-169.html), which defines Max#SAT). You probably want to use a MaxSAT solver like [MaxHS](http://www.maxhs.org/).

Anyway, I assume your confusion is based on the result that a random assignment will satisfy on average 7/8 of the clauses of any 3SAT instance. That only holds when each clause is really a 3SAT clause, i.e. contains 3 distinct variables, and therefore is satisfied with probability 7/8 by a random assignment. Some of your clauses are trivial (always satisfied) or simplify to only having 2 variables.
